apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: rslabel
  name: rslabel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rslabel
  template:
    metadata:
      labels:
        app: rslabel
    spec:
      containers:
      - image: nginx:1.7.1
        name: nginx