apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: world
  name: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: world
    spec:
      containers:
      - image: amitshah/world
        name: world
        resources: {}
status: {}
