apiVersion: batch/v1
kind: CronJob
metadata:
  name: bbcronjob
spec:
  jobTemplate:
    metadata:
      name: bbcronjob
    spec:
      template:
        metadata:
        spec:
          containers:
          - image: busybox
            name: bbcronjob
            command:
            - "echo"
            args:
            - "Hello CronJob"
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'