apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx1
  name: nginx1
spec:
  containers:
  - env:
    - name: dbhost
      valueFrom:
       configMapKeyRef:
         name: dbconfig1
         key: dbhost
    - name: dbport
      valueFrom:
       configMapKeyRef:
         name: dbconfig1
         key: dbport
    image: nginx
    name: nginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}