apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx3env
  name: nginx3env
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
        name: dbconfig3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
