apiVersion: v1
kind: Pod
metadata:
  labels:
    app: adapterpod
  name: adapterpod
spec:
  volumes:
   - name: logs
     emptyDir: {}
  containers:
  - volumeMounts:
    - name: logs
      mountPath: /etc/logs
    image: amitshah/fun
    name: app
  - volumeMounts:
    - name: logs
      mountPath: /etc/logs
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do sleep 30; echo 'Formatting logs..'; cat /etc/logs/fun.txt | tr [a-z] [A-Z]; done"
    image: busybox
    name: bb
  dnsPolicy: ClusterFirst
  restartPolicy: Never
