apiVersion: v1
kind: Pod
metadata:
  name: multicon
  labels:
    app: multicon
spec:
  containers:
  - name: nginx
    image: nginx:1.7.1
  - name: busybox
    image: busybox
    command:
    - "sleep"
    args:
    - "360"

