apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx55vol
  name: nginx55vol
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: mysec
      mountPath: /etc/secret
  volumes:
  - name: mysec
    secret:
      secretName: dbsec5
      items:
      - key: db.conf
        path: db
      - key: ops.conf
        path: ops
  dnsPolicy: ClusterFirst
  restartPolicy: Never
