apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx33vol
  name: nginx33vol
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: mysec
      mountPath: /etc/secret
  volumes:
  - name: mysec
    secret:
      secretName: dbsec3
      items:
      - key: db.conf
        path: db
  dnsPolicy: ClusterFirst
  restartPolicy: Never
