apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx33env
  name: nginx33env
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - secretRef:
        name: dbsec3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
