apiVersion: v1
kind: Pod
metadata:
  name: qos2
  namespace: default
  labels:
    app: qos2
spec:
  containers:
  - name: qos2
    image: alpine
    command:
    - "sleep"
    args:
    - "360"
    resources:
     requests:
       memory: "10Mi"
       cpu: "0.5"