apiVersion: v1
kind: Pod
metadata:
  name: scontext
  namespace: default
spec:
  securityContext:
    fsGroup: 3000
    runAsUser: 1000
  containers:
    - image: alpine
      name: alpine1
      command:
      - "sleep"
      args:
      - "360"
    - image: alpine
      name: alpine2
      securityContext:
        runAsUser: 2000
      command:
      - "sleep"
      args:
      - "360"