apiVersion: v1
kind: Pod
metadata:
  name: tolerate1
  namespace: default
  labels:
    app: tolerate1
spec:
  containers:
  - name: tolerate1
    image: alpine
    command:
    - "sleep"
    args:
    - "360"
  tolerations:
  - effect: "NoSchedule"
    key: "alpine"
    operator: "Exists"