apiVersion: v1
kind: Pod
metadata:
  name: tolerate2
  namespace: default
  labels:
    app: tolerate2
spec:
  containers:
  - name: tolerate2
    image: alpine
    command:
    - "sleep"
    args:
    - "360"
  tolerations:
  - effect: "NoSchedule"
    key: "alpine"
    operator: "Equal"
    value: "pod"