apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dep-surge
  name: dep-surge
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dep-surge
  template:
    metadata:
      labels:
        app: dep-surge
    spec:
      containers:
      - image: nginx:1.7.1
        name: nginx
