apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lbworld
  name: lbworld
spec:
  ports:
  - name: 7001-4001
    port: 7001
    protocol: TCP
    targetPort: 4001
  selector:
    app: world
  type: LoadBalancer
status:
  loadBalancer: {}
