apiVersion: v1
kind: Pod
metadata:
  labels:
    run: readyfun
  name: readyfun
spec:
  containers:
  - image: amitshah/fun
    name: readyfun
    readinessProbe:
       httpGet:
         scheme: HTTP
         path: /
         port: 4004
       initialDelaySeconds: 10
       periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
