apiVersion: v1
kind: Pod
metadata:
  labels:
    run: readynginx
  name: readynginx
spec:
  containers:
  - image: nginx
    name: readynginx
    readinessProbe:
       httpGet:
         scheme: HTTP
         path: /index.html
         port: 80
       initialDelaySeconds: 10
       periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
