apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bb2
  name: bb2
spec:
  volumes:
   - name: test
     hostPath:
       path: /home/vagrant/volumedata
  containers:
  - volumeMounts:
    - name: test
      mountPath: /etc/test
    command:
    - sleep
    - "3600"
    image: busybox
    name: busybox
  dnsPolicy: ClusterFirst
  restartPolicy: Never
