apiVersion: v1
kind: Pod
metadata:
  name: bb4
  labels:
    team: qa
    env: perf
  annotations:
    build: two
    builder: vashistha
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "360"]
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
